# Generated by Django 4.0 on 2022-01-03 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('emp_no', models.IntegerField()),
                ('mobile', models.CharField(max_length=15)),
                ('place', models.CharField(max_length=128)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registery.position')),
            ],
        ),
    ]
