# Generated by Django 4.0 on 2022-01-03 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='title',
            field=models.CharField(choices=[('JD', 'Junior Developer'), ('SD', 'Senior Developer'), ('DE', 'Devops Engineer')], max_length=50),
        ),
    ]
