# Generated by Django 4.0 on 2022-01-03 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registery', '0002_alter_position_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_no',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='position',
            name='title',
            field=models.CharField(choices=[('SL', 'SELECT'), ('JD', 'Junior Developer'), ('SD', 'Senior Developer'), ('DE', 'Devops Engineer'), ('TE', 'TEST Engineer'), ('PM', 'PROJECT Manager')], max_length=50),
        ),
    ]
